### ISSUE TITLE
[트러블슈팅] CI 파이프라인 구성 

### ISSUE THREAD

**Issue by jhbreeze** [TempLLO/templlo-booking-2025#31]
### ⚠️ 문제상황1. 최상위 디렉토리에서 gradle 빌드 시도 시 실패

![image](https://github.com/user-attachments/assets/8b9dc1a3-d00d-4213-9c66-f7e65aa0bfdb)

에러메시지 : `chmod: cannot access 'gradlew': No such file or directory`

### 원인
MSA 구조에서 각 서비스별로 독립적인 gradle 프로젝트가 구성되어 있어서 최상위 디렉토리에는 gradle 설정 파일이 존재하지 않음.

CI 파이프라인 최상위 디렉토리에서 빌드를 시도했으나, 서비스 디렉토리로 이동하지 않아 gradlew 파일을 찾을 수 없는 문제가 발생함.

### 해결방법
작업 디렉토리 설정으로 빌드 환경 지정
```
- name: Build and Test
  working-directory: ${{ matrix.service }}  # 각 서비스 디렉토리로 이동
  run: |
    echo "Building ${{ matrix.service }}"
    chmod +x gradlew
    ./gradlew clean build
``` 

### ⚠️ 문제상황2. CI 환경에서 테스트 실행 시 데이터베이스 연결 실패
![image](https://github.com/user-attachments/assets/0442f9a9-1c10-48ea-9fdf-db296128b8fb)
에러메시지
```
UserApplicationTests > contextLoads() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:180
        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1808
            Caused by: org.hibernate.service.spi.ServiceException at AbstractServiceRegistryImpl.java:276
                Caused by: org.hibernate.HibernateException at DialectFactoryImpl.java:191
```

### 원인
테스트 환경의 데이터베이스 설정이 불완전하여 발생. 
yml 파일에서 DB 정보를 환경변수로 처리하고 있는데 CI 환경에서 데이터베이스 환경변수가 제대로 설정되지않아 DB 연결 실패
```
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/templlo_user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
```

### 해결방법
1. test/resources/application.yml에 테스트용 DB 설정 추가하여 테스트환경 별도 분리 
```
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
```
2. H2 빌드 의존성 추가하여 테스트 DB 환경 구성 
```
dependencies {
    testRuntimeOnly 'com.h2database:h2'
}
```

### 의문점 
- MSA에서 각 서비스마다 테스트환경을 독립적으로 구성해야하는것이 맞는지 
- CI 파이프라인에서 별도 테스트환경 구성하는 방법이 있는지 

### ⚠️ 문제상황3. 워크플로우 동작 시, 매 번 모든 서비스 빌드로 인한 긴 빌드 시간 
![image](https://github.com/user-attachments/assets/c28c1a6e-3394-4f42-a4a1-4fb0ae0b068a)

### 원인
paths에 명시된 서비스에서 변경 사항이 발생하면, 해당 경로에서만 빌드 및 테스트가 진행되는줄 알았지만, 잘못된 빌드 전략을 설계함. paths는 트리거가 될 뿐 작업 디렉토리를 지정하는 역할이 아님. 즉, paths에 명시된 서비스 어디든 PR, push의 행위가 발생하면 워크플로우가 진행되는 트리거일 뿐임.
```
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
      ...
  push:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
     ...
```

### 해결방법
변경된 파일 경로를 감지하기 위한 changes job을 구성함. 이 job을 다른 job에서 참조할 수 있도록 구성하여, 특정 디렉토리에 변경이 있을 때만 해당 서비스가 빌드 대상이 되도록 설정함. 
```
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs: # 이 job의 결과를 다른 job에서 사용할 수 있도록 output 설정
      matrix: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2 # 어떤 서비스 디렉토리가 변경되었는지 감지
        id: filter
        with:
          filters: |
            gateway:
              - 'gateway/**'
            server:
              - 'server/**'
            user:
              - 'com.templlo.service.user/**'
          ...

```
![image](https://github.com/user-attachments/assets/f773f978-27e9-4160-8bff-bf664b357fd0)
변경된 서비스만 빌드 및 테스트하도록 수정하여 빌드 시간 단축(3분 16초 -> 1분 30초)
